### ISSUE TITLE
[Bug] Not Checked Artworks incomplete, stats not updating during update

### ISSUE THREAD

**Issue by bbsixzz** [BLeeEZ/amperfy#128]
iPhone SE 2016 iOS 15.5, Amperfy 1.1.0 (2)

The Cached Artwork stats don't update during Download all artworks in the library unless you go back and tap Artwork.

There are 2 Not Checked Artworks that never complete.

Download all artworks in library seems slow (fast server) and scrolling through all albums doesn't help to cache the last 2.

There seems to be no missing artwork however.

Maybe implement a link for Not Checked Artworks to see the problematic files when tapped?

![IMG_5837](https://user-images.githubusercontent.com/47334163/169923567-226d0ea9-6639-487d-a62d-95595fb65b98.PNG)

**Comment by BLeeEZ** [comment]
Yes this is a bug. The calculation of "Not Checked Artworks" was wrong.
It should be fixed with b3e79820dedefe20a87003370844c97f95a8112c.

**Comment by BLeeEZ** [comment]
Are the numbers now correct in the latest beta?

**Comment by bbsixzz** [comment]
Yes!

**Comment by bbsixzz** [comment]
The numbers are correct but they still don't update unless you leave the settings screen and come back.

**Comment by BLeeEZ** [comment]
I will add a periodic UI update.

**Comment by BLeeEZ** [comment]
The UI update is implemented in 9c11064042f983b9b3bb3c813b5751d815be0440.
