### ISSUE TITLE
Support for Ogg Vorbis

### ISSUE THREAD

**Issue by h-2** [BLeeEZ/amperfy#498]
I am opening a new issue because #145 is closed and cannot be re-opened. Since the most recent iOS upgrade stock applications like Safari support playing Ogg Vorbis, so the system libraries likely provide the capability now.

Would it be possible to upgrade amperfy to make use of this? Maybe it's just about targetting a newer versio of the the API?

I have 10'000s of songs in Ogg Vorbis on my server and can't transcode those just for the iPad.

Thank you!

**Comment by BLeeEZ** [comment]
I moved to AudioStreaming as player backend to support Equalizer and ReplayGain. AudioStreaming does not support Ogg Vorbis.

**Comment by h-2** [comment]
Vorbis hast been addwd Upstream!

**Comment by bitfl0wer** [comment]
I'd also like to express interest in OGG/Opus support! :)

**Comment by BLeeEZ** [comment]
Amperfy is now referencing AudioStreaming in version 1.4.0 (de8766984c4f2706df48802b61f1eda87c916b28). Ogg will thus be support in the next Amperfy release.

**Comment by tom-davies** [comment]
This seems to still be missing from the latest version (v2.1.0, build 15)

**Comment by adam-blackwater** [comment]
> This seems to still be missing from the latest version (v2.1.0, build 15)

It's included in the latest release :D 

Thank you BleeEZ

https://github.com/BLeeEZ/amperfy/releases/tag/v2.1.0#:~:text=Development

**Comment by igordiachkov** [comment]
opus files play, but there is no ability to seek within the track. Also, the total duration of the track is not displayed. Could you advise what might be causing this issue?

track metadata:
[media.json](https://github.com/user-attachments/files/26112382/media.json)

**Comment by rafalhycko** [comment]
I updated to version 2.1.0.

Streaming format (Raw/Original or Server Chooses Codec) does not matter—the file will not play. I am using Gonic.

Below is the audio file metadata:

Audio
ID: 1674731565 (0x63D2602D)
Format: Opus
Duration: 1 min 37 s
Channels: 2 (L, R)
Sampling rate: 48.0 kHz
Compression mode: Lossy
Writing library: Lavf61.4.100
Language: English

**Comment by raisinbear** [comment]
> I updated to version 2.1.0.
> 
> Streaming format (Raw/Original or Server Chooses Codec) does not matter—the file will not play. I am using Gonic.
> 
> Below is the audio file metadata:
> 
> Audio ID: 1674731565 (0x63D2602D) Format: Opus Duration: 1 min 37 s Channels: 2 (L, R) Sampling rate: 48.0 kHz Compression mode: Lossy Writing library: Lavf61.4.100 Language: English

Same for me. Still tells me to enable transcoding to play Vorbis media on 2.1.0.

**Comment by rafalhycko** [comment]
> Same for me. Still tells me to enable transcoding to play Vorbis media on 2.1.0.

Are you using Gonic? 
How can it be that some can play opus and some cannot?

**Comment by raisinbear** [comment]
> > Same for me. Still tells me to enable transcoding to play Vorbis media on 2.1.0.
> 
> Are you using Gonic? How can it be that some can play opus and some cannot?

Sorry just saw your post was about Opus. I was trying to play Vorbis, which still doesn’t work (with Navidrome).

**Comment by rafalhycko** [comment]
I see. Still don't understand how @igordiachkov is able to play Opus. @BLeeEZ could you confirm that Amperfy plays Opus and that the problem is on my side?

**Comment by BLeeEZ** [comment]
I didn't had OGG files previously in my library. I now added files and tested it with it.
There was an issue with the MIME type filter: "audio/ogg", "application/ogg" was marked as incompatible. So if the meme type is different it can be played.

I fixed it via 32e7125c84f305bb1f2044286fe98e81162701c0.
Now the playback for those MIME types works as expected.

**Comment by rafalhycko** [comment]
Thank you very much 👍

**Comment by Bammede** [comment]
Still the ios app not playing Opus files

**Comment by muffinsAKA** [comment]
> Still the ios app not playing Opus files

Since the previous comments there has not been a new version released on iOS so I don't think the change has made it to the app.

**Comment by tom-davies** [comment]
Opus files still won't play, streamed or downloaded. The details under the playback bar show

[downloaded icon] OGG [original FLAC file bitrate]

Client is Amperfy v2.1.1(22)
Server is Navidrome 0.63.2

**Comment by adam-blackwater** [comment]
I don't get Opus files playing either. However there does seem to be progress. The Amperfy player doesn't show the blue error message and the music server (Navidrome 0.63) seems to think the file is playing as I can see activity in the logs for Navidrome when trying to play the Opus file in Amperfy. There is no audio from Amperfy though

**Comment by BLeeEZ** [comment]
This can be tested in the lasted Amperfy Beta v2.1.1 (22) via TestFlight: https://github.com/BLeeEZ/amperfy/issues/25

**Comment by tom-davies** [comment]
@BLeeEZ I am using v2.1.1(22), and Opus files still won't play. Nothing is listed in the Event Log either

**Comment by FaintWhisper** [comment]
> [@BLeeEZ](https://github.com/BLeeEZ) I am using v2.1.1(22), and Opus files still won't play. Nothing is listed in the Event Log either

I also just tested this new version via Testflight and can confirm this exact behavior: no error message appears now, but Opus files still won't play.

They were transcoded using "Server chooses codec format," and on the server, I configured Opus at a maximum bitrate of 128 kbps with this ffmpeg command: ffmpeg -nostdin -hide_banner -loglevel error -ss %t -i %s -map 0:a:0 -vn -sn -dn -c:a libopus -b:a 128k -vbr on -compression_level 10 -application audio -f opus
